name: Regression End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: windows-latest # Change the operating system to Windows

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use the setup-node action to set up Node.js on Windows
        with:
          node-version: "14" # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install # Install npm dependencies

      - name: Cypress run
        run: npx cypress run # Run Cypress tests with npx on Windows

      - name: Cypress run on Windows
        run: npx cypress run --browser chrome
